"use client";
/* eslint-disable @next/next/no-img-element */

import { FormEvent, useState } from "react";
import { cabins, type CabinType } from "../src/data/coupleCruiseProduct";
import { company } from "../src/config/company";
import { track } from "../src/lib/analytics";

const scrollTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
const faqs = [
  ["크루즈가 처음인데도 괜찮을까요?", "네. 부산항 집결부터 귀국 이동까지 전문 인솔자가 단계별로 안내합니다. 처음 타시는 두 분도 일정 흐름을 쉽게 따라오실 수 있도록 상담 때 미리 설명드립니다."],
  ["배멀미가 걱정됩니다.", "날씨와 개인 컨디션에 따라 다를 수 있어요. 필요 시 상담을 통해 객실 위치와 준비 방법을 안내해 드립니다."],
  ["상품가 외에 무엇을 확인해야 하나요?", "객실 위치·항공편·예약 시점에 따라 최종 금액이 달라질 수 있습니다. 선내 서비스 차지, 세금, 항공편별 추가금 등은 상담 시 투명하게 안내합니다."],
  ["상담 신청하면 바로 예약되는 건가요?", "아닙니다. 상담 신청은 객실과 예상 총비용을 확인하는 단계이며, 예약 확정이나 결제가 아닙니다."],
];

function ImageArea({ name, label }: { name: string; label: string }) {
  const [missing, setMissing] = useState(false);
  if (missing) return <div className="image-placeholder" aria-label={`${label} 이미지 준비 중`}><span>CRUISEYA</span><b>{label}</b><small>새 이미지가 추가되면 자동으로 표시됩니다</small></div>;
  return <img src={`/images/cruise-couple/${name}`} alt={label} onError={() => setMissing(true)} />;
}

export function CruiseLanding() {
  const [menu, setMenu] = useState(false); const [selected, setSelected] = useState<CabinType>("ocean"); const [openFaq, setOpenFaq] = useState<number | null>(null); const [toast, setToast] = useState(""); const [submitted, setSubmitted] = useState(false);
  const choose = (type: CabinType, location: string) => { setSelected(type); track("cabin_select", { cabinType: type, ctaLocation: location }); scrollTo("consultation"); };
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3500); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); if (!data.get("privacy") || !data.get("terms")) { notify("개인정보 수집 동의와 특별약관 확인이 필요합니다."); return; } track("consultation_submit", { cabinType: selected }); setSubmitted(true); track("consultation_success", { cabinType: selected }); };
  return <>
    <a className="skip" href="#content">본문으로 건너뛰기</a>
    <header><a className="brand" href="#top">CRUISEYA <small>주식회사 크루즈야</small></a><nav aria-label="주요 메뉴"><a href="#itinerary">여행 일정</a><a href="#cabins">객실 안내</a><a href="#faq">자주 묻는 질문</a></nav><button className="nav-cta" onClick={() => scrollTo("consultation")}>객실 상담 신청</button><button className="menu" aria-label="메뉴 열기" aria-expanded={menu} onClick={() => setMenu(!menu)}>☰</button></header>
    {menu && <div className="mobile-menu"><a onClick={() => setMenu(false)} href="#itinerary">여행 일정</a><a onClick={() => setMenu(false)} href="#cabins">객실 안내</a><button onClick={() => { setMenu(false); scrollTo("consultation"); }}>객실 상담 신청</button></div>}
    <main id="content">
      <section className="hero" id="top"><ImageArea name="hero-couple-cruise.png" label="부산항에서 크루즈를 바라보는 부부"/><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">BUSAN · KOBE · 2026.09.12</p><h1>두 분의 특별한 여행,<br/>부산에서 편안하게 시작하세요</h1><p>크루즈가 처음이어도 전문 인솔자의 안내와 함께<br/>숙박·식사·공연·고베 관광을 한 번에 즐기는 2박 3일</p><div className="facts"><span>부산항 출발</span><span>코스타 세레나호</span><span>1인 98만 원부터</span></div><button className="primary" onClick={() => {track("hero_cta_click", { ctaLocation: "hero" }); scrollTo("consultation");}}>두 분께 맞는 객실 추천받기</button><small>상담 신청은 예약 확정이나 결제가 아닙니다.</small></div></section>
      <section className="intro section"><p className="eyebrow navy">처음이라 더 편안해야 하니까</p><h2>복잡한 이동은 줄이고,<br/>두 분의 시간은 더 넉넉하게</h2><p className="lead">부산에서 출발해 바다 위의 숙소에서 쉬고, 일본 고베까지 만나는 여행입니다. 집결부터 귀국까지 전문 인솔자가 함께해 처음인 크루즈도 차분하게 시작하실 수 있습니다.</p><div className="three"><article><b>01</b><h3>부산항에서 바로 출발</h3><p>먼 곳 공항까지 이동하는 부담을 덜었습니다.</p></article><article><b>02</b><h3>숙박과 식사가 한 번에</h3><p>짐을 옮길 일 없이 선내에서 편안하게 머뭅니다.</p></article><article><b>03</b><h3>전문 인솔자 동행</h3><p>낯선 절차와 일정도 단계별로 안내합니다.</p></article></div></section>
      <section className="route section"><p className="eyebrow gold">여행의 흐름</p><h2>부산에서 출발해, 고베의 하루까지</h2><div className="route-line"><div><strong>DAY 1</strong><span>부산항 집결 · 승선</span></div><i>→</i><div><strong>DAY 2</strong><span>선상 휴식 · 고베 도착</span></div><i>→</i><div><strong>DAY 3</strong><span>고베 관광 · 공항 이동</span></div></div><p>고베 관광 후 간사이 지역 공항으로 이동하여 부산·인천·청주 방면 항공편 중 선택합니다. 항공편별 시간과 추가금은 상담 시 안내드립니다.</p></section>
      <section id="itinerary" className="section"><p className="eyebrow navy">2박 3일 일정</p><h2>바쁘게 채우기보다, 여유 있게 누리는 시간</h2><div className="timeline"><article><span>DAY 1</span><h3>부산항에서 설렘을 싣고 출발</h3><p>국제여객터미널 집결 후 인솔자 안내에 따라 승선합니다. 객실에 짐을 풀고 선상 식사와 공연을 즐겨보세요.</p></article><article><span>DAY 2</span><h3>바다 위의 하루, 그리고 고베</h3><p>여유로운 선상 아침과 다양한 프로그램을 경험한 뒤, 일본 고베의 항구 도시 풍경을 만납니다.</p></article><article><span>DAY 3</span><h3>여행의 여운을 안고 귀국</h3><p>고베 관광 후 간사이 지역 공항으로 이동합니다. 선택하신 귀국 항공편에 맞춰 안내해 드립니다.</p></article></div></section>
      <section className="experience"><div><ImageArea name="balcony-couple.webp" label="발코니에서 바다를 보는 부부"/></div><div className="experience-copy"><p className="eyebrow gold">두 분만의 기념일</p><h2>평소와 다른 식사,<br/>함께 바라보는 바다</h2><p>결혼기념일, 은퇴 기념, 생일. 특별한 이유가 있는 여행이라면 객실에서도 바다를 느낄 수 있는 오션뷰와 발코니를 먼저 살펴보세요.</p><button className="outline-light" onClick={() => { track("anniversary_cta_click", { ctaLocation: "experience" }); choose("balcony", "experience"); }}>기념일 객실 상담받기</button></div></section>
      <section id="cabins" className="section cabin-section"><p className="eyebrow navy">객실 선택</p><h2>두 분의 여행 방식에 맞춰 고르는 객실</h2><p className="lead">모든 가격은 2인 1실 사용 시 1인 기준입니다. 객실 위치·잔여 객실·항공편과 예약 시점에 따라 최종 금액이 달라질 수 있습니다.</p><div className="cabins">{cabins.map(c => <article className={`cabin ${c.recommended ? "recommended" : ""}`} key={c.type}>{c.recommended && <em>부부 여행 추천</em>}<p className="cabin-type">{c.type === "ocean" ? "OCEAN VIEW" : c.type === "balcony" ? "BALCONY" : "INSIDE"}</p><h3>{c.name}</h3><strong>{c.price}</strong><p>{c.note}</p><button onClick={() => choose(c.type, "cabin")}>{c.name} 객실 문의하기</button></article>)}</div></section>
      <section className="included section"><p className="eyebrow navy">투명하게 안내드립니다</p><h2>무엇이 포함되고, 무엇을 확인해야 할까요?</h2><div className="two"><article><h3>기본 포함 안내</h3><ul><li>크루즈 선내 숙박</li><li>선내 기본 식사 및 공연</li><li>일본 고베 관광 일정</li><li>전문 인솔자 동행 안내</li></ul></article><article><h3>상담 전 확인 사항</h3><ul><li>항공편별 귀국 시간과 추가금</li><li>선내 서비스 차지 및 세금</li><li>객실 위치별 최종 금액</li><li>여행자보험 및 최종 취소약관</li></ul></article></div><p className="notice">포함 범위와 불포함 비용은 확정된 예약 조건에 따라 상담 시 상세히 안내드립니다.</p></section>
      <section className="guide section"><p className="eyebrow gold">크루즈 초보자 안내</p><h2>처음 타는 크루즈, 이렇게 준비하시면 됩니다</h2><div className="three"><article><b>1</b><h3>상담으로 객실과 비용 확인</h3><p>두 분의 여행 목적과 귀국 지역에 맞춰 차분히 안내합니다.</p></article><article><b>2</b><h3>부산항에서 인솔자 미팅</h3><p>집결부터 승선 절차까지 함께 안내받습니다.</p></article><article><b>3</b><h3>여유롭게 여행 즐기기</h3><p>선내 숙박·식사·공연과 고베의 하루를 누립니다.</p></article></div></section>
      <section id="faq" className="section faq"><p className="eyebrow navy">자주 묻는 질문</p><h2>처음이라 궁금한 점, 미리 답해드립니다</h2>{faqs.map(([q,a], i) => <article key={q}><button aria-expanded={openFaq === i} aria-controls={`faq-${i}`} onClick={() => { setOpenFaq(openFaq === i ? null : i); track("faq_open", { ctaLocation: `faq_${i}` }); }}><span>{q}</span><b>{openFaq === i ? "−" : "+"}</b></button>{openFaq === i && <p id={`faq-${i}`}>{a}</p>}</article>)}</section>
      <section id="consultation" className="consultation"><div><p className="eyebrow gold">객실 맞춤 상담</p><h2>두 분께 맞는 객실과<br/>예상 총비용을 확인해 보세요</h2><p>상담 신청은 예약 확정이나 결제가 아닙니다. 편하신 시간에 여행 전문가가 안내드립니다.</p><div className="contact"><strong>전화 상담</strong><span>{company.phone}</span><button onClick={() => {track("phone_click", { ctaLocation: "consultation" }); notify("대표 전화는 운영 전 등록 예정입니다.");}}>전화 상담 안내</button></div></div><form onSubmit={submit}>{submitted ? <div className="success" role="status"><h3>상담 신청을 접수했습니다.</h3><p>운영 환경에서 상담 API가 연결되면 담당자가 연락드립니다.</p></div> : <><label>관심 객실<select value={selected} onChange={e => setSelected(e.target.value as CabinType)}><option value="ocean">오션뷰 (추천)</option><option value="balcony">발코니</option><option value="inside">인사이드</option></select></label><label>성함<input name="name" required placeholder="성함을 입력해 주세요"/></label><label>연락처<input name="phone" required inputMode="tel" placeholder="연락처를 입력해 주세요"/></label><label>여행 목적<select name="purpose"><option>결혼기념일</option><option>은퇴 기념</option><option>생일 기념</option><option>부부 여행</option></select></label><label className="check"><input name="privacy" type="checkbox"/> 개인정보 수집 및 이용에 동의합니다.</label><label className="check"><input name="terms" type="checkbox"/> 국외여행 특별약관을 확인했습니다.</label><button className="primary full" type="submit" onClick={() => track("consultation_start", { cabinType: selected })}>객실 추천 상담 신청하기</button><small>입력하신 정보는 상담 목적 외에 사용하지 않습니다.</small></>}</form></section>
      <section id="final-cta" className="final"><p className="eyebrow gold">2026.09.12 · 부산항 출발 · 코스타 세레나호</p><h2>두 분의 새로운 여행,<br/>부산에서 시작해 보세요</h2><p>바다를 바라보며 함께 식사하고, 공연을 즐기고, 일본 고베의 하루까지 만나는 2박 3일.</p><button className="primary" onClick={() => {track("final_cta_click", { ctaLocation: "final" }); scrollTo("consultation");}}>두 분의 객실 가능 여부 확인하기</button><button className="text-button" onClick={() => {track("kakao_click", { ctaLocation: "final" }); notify("카카오톡 상담 채널을 준비 중입니다.");}}>카카오톡으로 부부 여행 문의하기</button></section>
    </main>
    <footer><strong>CRUISEYA</strong><p>주식회사 크루즈야</p><p>대표 전화 {company.phone} · 대표자 {company.ceo} · {company.address}</p><p>사업자등록번호 {company.registration} · 통신판매업 신고번호 {company.salesRegistration} · 개인정보관리 책임자 {company.privacyManager}</p><p><a href="#">개인정보처리방침</a> <a href="#">이용약관</a> <a href="#faq">국외여행 특별약관</a></p><small>Copyright © CRUISEYA. All rights reserved.</small></footer>
    <div className="mobile-bar"><small>부부 2인 기준 객실 맞춤 상담</small><button onClick={() => notify("대표 전화는 운영 전 등록 예정입니다.")}>전화 상담</button><button onClick={() => scrollTo("consultation")}>객실 추천받기</button></div>{toast && <div className="toast" aria-live="polite">{toast}</div>}
  </>;
}
